spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
      profiles: native
server:
  port: 8888

endpoints:
  restart:
    enabled: true